package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
)

func main() {

	router()

}

func gifs(w http.ResponseWriter, r *http.Request) {
	search := "hasbullah"

	giphyKey := os.Getenv("GIPHY_KEY_TEST")
	url := fmt.Sprintf("https://api.giphy.com/v1/gifs/search?api_key=%s&q=%s&limit=25&offset=0&rating=g&lang=en", giphyKey, search)

	w.Header().Set("Content-Type", "application/json")

	resp, err := http.Get(url)
	if err != nil {
		fmt.Println("err", err)
	}

	data := &AutoGenerated{}

	err = json.NewDecoder(resp.Body).Decode(&data)
	if err != nil {
		fmt.Println("error", err)
		return
	}

	// fmt.Fprintf(w, fmt.Sprintf("%v", data.Data[0].Images))
	json.NewEncoder(w).Encode(data)

}

func router() {
	http.HandleFunc("/", gifs)

	fmt.Println("serving on port 8080")
	http.ListenAndServe(":8080", nil)
}

type Data struct {
	Gifs []*Gif
}

type Gif struct {
	ID  string `json:"id"`
	URL string `json:"url"`
}
